* Communication Codes for space mud
Your ship comes preinstalled with a standard DSN-225 communication module, which uses short hexadecimal sequences to transmit data long distance.

Your ship also comes with a manual for understanding what these messages mean, there is also a search function in your ships computer to find commands.

Some messages are encrypted using third-party encryption modules such as the Axotekisha KSR-23 (or AK for short) which shift the digits of the command to attempt to stop non-approved personnel from reading their messages. In order to read these encrypted modules you either need to guess the cipher or purchase the module for your own ship.

Just because a messages says that it's from one party does not guarantee it is from that party, it's possible to spoof your identity due to an exploit in the DSN-225's hardware.

** Format
- All communcation codes are formated in 4 digit hex number
- Ship oriented commands are a 2 digit number prefixed with an M
- Special communcations contain a 1-2 character header, these messages can only be read using specialized equipment
  + Without the hardware, the true manual index cannot be viewed, as the number has been in some way obscured.
- Response codes are a 3 Digit hexadecimal number preceeded by an R
- Standard Message example
  + 1132 - Repeat your last message.
  + 1A3F - Are you selling anything?
  + 0324 - I come in peace
- Ship command example
  + M0C - Scan current system for other objects
  + M04 - Coordinates of closest object
- Specialized Message example
  + AF2243 - Repeat your last message. (encrypted without specific hardware - number is shifted somehow)
  + AA4652 - Are you selling anything? (again, encrypyted)
- Return example
  + R000 - Command is not valid
  + RFFF - unknown error occured

** Full unencrypted command list
`Coming soon!`
