* How to play
** The basics
Space-Mud is based on communication using a predefined set of Hexidecimal sequences.

There are a few commands that are in plain english in order to help out new players, mainly search, man, and help.

*** man
man is the manual command, this is how you can look up what a recieved command means
- example:
  + man 1132
    - searches for the definition of 1132 (Repeat your last message)
*** search
search searches for a command given a keyword
- example:
  + search repeat
    - searches for commands containing the word "repeat" (would return 1132)

*** help
brings up a simple help menu explaining basic commands and gameplay, just type help to use it.

** How communication works
In Space-Mud in order to issue communications to a specific ship you must be inside of the same system as the ship you are attempting to communicate with.

In order to find out which ships are in your system issue the system command M0C, this command will return the ships in your current system.

** Fuel
By default you start with 10fr of fuel, this is enough to travel a good distance. In order to obtain must fuel you must either scavenge a ship or buy it.

** The Economy
Coming Soon!

** Combat
Coming Soon!
